### ISSUE TITLE
Compatibility with M1 processor

### ISSUE THREAD

**Issue by rogelio-alb** [bertrandplez/Turbospectrum_NLTE#13]
Hello, 

I've been using this package for my science for a while now. I recently got a new computer and I've been trying to run TSv20 without much success. 

This is likely due to ifort not being available for M1 processors, but since the gfortran version is no longer supported from what I can see in the documentation file, this leaves me in a difficult spot.

If there is a way to run the code in M1, can you please post a tutorial? 

Thanks in advance

**Comment by bertrandplez** [comment]
Hi,

I just checked, and it compiles fine with gfortran [gcc version 13.1.0 (Homebrew GCC 13.1.0)] on my Mac intel core i7. Try compiling in exec-gf/
Hope it works!

**Comment by rogelio-alb** [comment]
Hello, thank you for the early response,

As you said, with the gfortran version, the compiling ends, and I see the usual files in exec-gf/. However, I get the following error when I try to run my scripts that worked on my other PC with ifort version.

`dyld[5381]: dyld cache '(null)' not loaded: syscall to map cache into shared region failed
dyld[5381]: Library not loaded: [/usr/lib/libSystem.B.dylib](https://file+.vscode-resource.vscode-cdn.net/usr/lib/libSystem.B.dylib)
  Referenced from: <16858B19-D455-3EC3-B3D5-F1CADCE868CC> [/path-to-ts/exec-gf/bsyn_lu](https://file+.vscode-resource.vscode-cdn.net/path-to-ts/exec-gf/bsyn_lu)
  Reason: tried: '/usr/lib/libSystem.B.dylib' (no such file)`

I think this problem is specific to the latests versions of MacOSX and M1 processors, where some binary files can no longer be found in `/usr/lib/`, do you know how to fix this problem? 

Another point that I wanted to ask. The documentation explicitly says that the gfortran version "does not work, as many older Fortran features are not supported anymore", so should I be worried that if I proceed with the gfrotran version I will get frequent bugs or noticeable differences in the synthetic spectra?

Thanks in advance.

**Comment by bertrandplez** [comment]
OK, thanks!
Fortran statements that were incompatible with gfortran were removed some time ago, but the doc hadn't been updated. Done now.

Regarding the library thing, you should check that you include the proper path in your LIBRARY_PATH, maybe.
Or possibly change -mcmodel=medium to -mcmodel=large in Makefile?
From looking around on the web at similar errors with M1/M2 Macs, I suspect that might not be easy to solve. Let me know.

**Comment by rogelio-alb** [comment]
Hi!
Modifying the Makefile does not change the error message. I checked for the path of the file `libSystem.B.dylib`, but it does not exist anywhere on the machine.

I've looked for people with similar problems and the closest thing I found is in this link:
https://developer.apple.com/forums/thread/722360

However, I did not see an easy fix. Let me know if you have any ideas, cheers.

**Comment by bertrandplez** [comment]
Have you tried to decrease NDP and point in spectrum.inc.
E.g use: ndp =100, and lpoint = 100000.
This will decrease the amount of used memory by a factor of about 15, if you were trying 150 and 1000000, which requires almost 4GB.

**Comment by bertrandplez** [comment]
I compiled the code on an M3 Mac with gfortran. 
It compiles and runs fine with -mcmodel=small.

**Comment by danangsetyo5364** [comment]
> I compiled the code on an M3 Mac with gfortran. It compiles and runs fine with -mcmodel=small.

Hello! could you give me a brief explanation how to solve it? because I couldn't use spherical model when running the TS on my M4 Mac. Thanks in advance for your help!

**Comment by danangsetyo5364** [comment]
Thank you very much for your help! I'm looking forward for any progress...

**Comment by danangsetyo5364** [comment]
Hai! Do you have any progress about this problem? or do you have any other suggestion?

Thanks in advance!
