### ISSUE TITLE
Solar abundances - documentation

### ISSUE THREAD

**Issue by uheiter** [bertrandplez/Turbospectrum_NLTE#18]
The documentation states that the default solar abundances are from Grevesse et al. (2007), while they are actually from Magg et al. (2022) according to input.f:
https://github.com/bertrandplez/Turbospectrum_NLTE/blob/8d8cad0856f09d9fa34e59199fd24dfeb28447b5/source/input.f#L51

Also, the keyword ABUND_SOURCE is not mentioned in the documentation.

**Comment by bertrandplez** [comment]
Thanks for pointing it out.
This is corrected. The default abundance is indeed Grevesse et al. 2007, and the Keyword appears in the documentation.
