### ISSUE TITLE
Interpolation Failed

### ISSUE THREAD

**Issue by danangsetyo5364** [bertrandplez/Turbospectrum_NLTE#22]
Hei! I want to calculate the abundance of my sample very metal-poor stars, with param: Teff = 44000, logg=0.1, and [Fe/H] = -3.7, AND I got error message: 
`Interpolation failed? 'NoneType' object is not subscriptable
didn't generate spectra or atmosphere` 

Do you know how to overcome this? I already check all the MARCS model atmosphere, and I have downloaded it all.

**Comment by bertrandplez** [comment]
Hi,

these parameters are totally outside the range allowed by MARCS models.

**Comment by danangsetyo5364** [comment]
ah sorry, i mistaken write the temperature, the correct one is 4400K. How about these one?

**Comment by stormnick** [comment]
You can see the MARCS grid coverage here btw (Fig.1 in https://ui.adsabs.harvard.edu/abs/2023A%26A...669A..43G/abstract). 

At logg around 0, the original MARCS doesn't go down to FeH = -3.7, that's why you run into the issue.

**Comment by bertrandplez** [comment]
The gravity is probably too low.
You can check the parameter range of the initial grid.

**Comment by danangsetyo5364** [comment]
OK, thanks for your advice! I already discussed this problem with my supervisor, and we have solved it. Thanks!
