### ISSUE TITLE
IR spectrum fitting fails in M4 Mac

### ISSUE THREAD

**Issue by danangsetyo5364** [bertrandplez/Turbospectrum_NLTE#23]
Hello, I just got my new MacBook and I want to run TS here. I have some experience to install and run this program on Windows/WSL before and it run smoothly. However, when I try to calculate abundance for an element (again I have checked that all the parameters are same, also the needed files), and TS could not synthesize the spectra, and chi_sq show : chi_sq=99999.

However when I test to run with template given by TSFit.py, it run as usual. anybody have same problem here?

**Comment by stormnick** [comment]
Maybe https://github.com/TSFitPy-developers/TSFitPy/issues is a bit more relevant. 

You can try running with debug_mode = 2 in the TSFitPy config and see the output. It is hard to say whether it is problem of TS, fortran or something else without it.

**Comment by danangsetyo5364** [comment]
hello, thanks for your quick reply, however I think I found the problem, the reason why when I tried to fit sun spectra, but not with my stars is because TS can not using spherical atmosphere model MARCS. I don't know the reason, I never met this situation when I ran it on WSL.

**Comment by stormnick** [comment]
Same issue as this perhaps?
https://github.com/bertrandplez/Turbospectrum_NLTE/issues/17

**Comment by danangsetyo5364** [comment]
yeah I already check it, and It seems there is no satisfy solution for this problem isn't it?

**Comment by bertrandplez** [comment]
See https://github.com/bertrandplez/Turbospectrum_NLTE/issues/17#issuecomment-2506515304

**Comment by danangsetyo5364** [comment]
Thank you very much! It solves the problem.
