### ISSUE TITLE
The error of `relocation truncated to fit` during make

### ISSUE THREAD

**Issue by MingjieJian** [bertrandplez/Turbospectrum_NLTE#6]
When I was running `make` in exec\, ifort gave some errors like:

```
bsyn.f:226:(.text+0x65): relocation truncated to fit: R_X86_64_PC32 against symbol `h2ochoice_' defined in COMMON section in /tmp/ifortO6D6Ji.o
bsyn.f:227:(.text+0x6c): relocation truncated to fit: R_X86_64_PC32 against symbol `h2ochoice_' defined in COMMON section in /tmp/ifortO6D6Ji.o
bsyn.f:228:(.text+0x73): relocation truncated to fit: R_X86_64_PC32 against symbol `h2ochoice_' defined in COMMON section in /tmp/ifortO6D6Ji.o
```

This seems to be related to the [memory model of ifort](https://www.ibm.com/support/pages/intel-compiler-error-relocation-truncated-fit-rx8664pc32). 
Since the default memory model (at least in my computer, Ubuntu 20.04) is small, this error should appear when one of the variable has a large size (>2GB).
I added `-mcmodel=medium` at the end of `LINKOPT`. 
Maybe it would also be convenient to add it to the repository?

Thank you in advance.

Mingjie

**Comment by EkaterinaSe** [comment]
Hi Mingjie,

indeed the issue is know, I just updated the repo, thanks for pointing out!

**Comment by EkaterinaSe** [comment]
Hi Mingjie,

just fyi, I commented out the mcmodel in the default makefile as it is not supported by macOS and windows versions of ifort
